config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include(debug_toolbar.urls)),
    path('polls/', include('polls.urls')),

]

polls/urls.py
from django.urls import path
from django.views.generic import detail

from polls import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(), name='results'),
    path('<int:pk>/vote/',views.vote, name='vote'),
]

polls/models.py
from django.contrib import admin
from django.utils import timezone
import datetime
from django.utils import timezone
from django.db import models


class Question(models.Model):
    objects = models.Manager()
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,  # نمایش به صورت تیک سبز/قرمز به جای True/False
        ordering="pub_date",  # امکان مرتب‌سازی بر اساس pub_date
        description="Published recently?",  # عنوان ستون در ادمین
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    objects = models.Manager()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.contrib import messages
from django.db.models import QuerySet, F
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'

    def get_queryset(self) -> QuerySet:  # در صفحه با question_list در دسترس هست
        """
        Return the last five published questions (not including those set to be published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
class DetailView(generic.DetailView):
    model = Question  # در صفحه با question در دسترس هست
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


# def detail(request, pk):
#     question: Question = get_object_or_404(Question, pk=pk)
#     choices: QuerySet[Choice] = question.choice_set.all()
#     context = {
#         'question': question,
#         'choices': choices,  # اینجوری اتوکامپلیت کار می کنه
#     }
#     return render(request, 'polls/detail.html', context)

def vote(request, pk):
    question: Question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        choice_id = request.POST.get('choice')
        if not choice_id:
            messages.error(request, "You didn't select a choice")
            return redirect('polls:detail', pk=question.pk)
        else:
            try:
                selected_choice = question.choice_set.get(pk=choice_id)
            except Choice.DoesNotExist:
                messages.error(request, "Invalid choice")
                return redirect('polls:detail', pk=question.pk)

            selected_choice.votes = F('votes') + 1
            selected_choice.save()
            messages.success(request, "Your vote was recorded!")
            return redirect('polls:results', pk=question.pk)
    else:
        return render(request, 'polls/detail.html', {
            'question': question,
            'choices': question.choice_set.all()
        })


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
# def results(request, pk):
#     question: Question = get_object_or_404(Question, pk=pk)
#     choices: QuerySet[Choice] = question.choice_set.all()
#     context = {
#         'question': question,
#         'choices': choices,
#     }
#     return render(request, 'polls/results.html', context)

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' pk=question.id %}" method="post">
    {% csrf_token %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <title>Polls List</title>
</head>
<body>
<h1>Polls</h1>
<ul>
    {% for question in question_list %}
        <li><a href="{% url 'polls:detail' pk=question.id %}">{{ question.question_text }}</a></li>
    {% empty %}
        <li>No questions found.</li>
    {% endfor %}
</ul>
</body>
</html>

polls/templates/polls/results.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>